import { DomainConfig, ProblemDomain } from './types';

export const DOMAIN_DATA: Record<ProblemDomain, DomainConfig> = {
  calculator: {
    name: 'Basic Calculator',
    description: 'Arithmetic calculations, PEMDAS evaluation, percentages, powers, roots, scientific logs, fractions, and angle-mode trigonometry.',
    operations: [
      { id: 'eval', name: 'Arithmetic & Order of Operations (PEMDAS)', defaultExpr: '25 * (4 + 16) / 5 - 2^3', params: ['precision'] },
      { id: 'percentage', name: 'Percentages, Markup & Discounts', defaultExpr: '15% of 240', params: [] },
      { id: 'powers_roots', name: 'Powers, Exponents & Roots', defaultExpr: 'sqrt(144) + 3^4 - cbrt(125)', params: [] },
      { id: 'trig_calc', name: 'Trigonometry & Inverse Functions', defaultExpr: 'sin(30) + cos(60)', params: ['angle_mode'] },
      { id: 'log_exp', name: 'Logarithms (log₁₀, ln, log₂) & Exp', defaultExpr: 'log10(1000) + ln(e^2)', params: [] },
      { id: 'fractions', name: 'Exact Fractions & Mixed Numbers', defaultExpr: '5/6 + 7/12 - 1/4', params: [] },
      { id: 'number_theory', name: 'GCD, LCM & Modulo Arithmetic', defaultExpr: 'gcd(48, 180)', params: [] },
    ],
    presets: [
      { label: '25 × (4+16) ÷ 5 - 2³', op: 'eval', expr: '25 * (4 + 16) / 5 - 2^3' },
      { label: '15% of 240', op: 'percentage', expr: '15% of 240' },
      { label: '250 + 15% (Markup)', op: 'percentage', expr: '250 + 15%' },
      { label: 'sin(30°) + cos(60°)', op: 'trig_calc', expr: 'sin(30) + cos(60)', params: { angle_mode: 'deg' } },
      { label: '√144 + 3⁴ - ∛125', op: 'powers_roots', expr: 'sqrt(144) + 3^4 - cbrt(125)' },
      { label: '5/6 + 7/12 - 1/4', op: 'fractions', expr: '5/6 + 7/12 - 1/4' },
      { label: 'log₁₀(1000) + ln(e²)', op: 'log_exp', expr: 'log10(1000) + ln(e^2)' },
      { label: 'gcd(48, 180)', op: 'number_theory', expr: 'gcd(48, 180)' },
    ],
  },
  calculus: {
    name: 'Calculus',
    description: 'Symbolic differentiation, integration, limits, Taylor series, and ODEs.',
    operations: [
      { id: 'diff', name: 'Derivative (d/dx)', defaultExpr: 'x^3 + sin(x)', params: ['variable', 'order'] },
      { id: 'integrate', name: 'Integral (Definite / Indefinite)', defaultExpr: 'x^2 * exp(x)', params: ['variable', 'bounds'] },
      { id: 'limit', name: 'Limit', defaultExpr: 'sin(x) / x', params: ['variable', 'point', 'direction'] },
      { id: 'series', name: 'Taylor Series Expansion', defaultExpr: 'cos(x)', params: ['variable', 'point', 'order'] },
      { id: 'ode', name: 'Differential Equation (ODE)', defaultExpr: 'diff(y(x), x, 2) + 4*y(x)', params: ['variable'] },
      { id: 'double_integral', name: 'Double Integral (dx dy)', defaultExpr: 'x^2 + y^2', params: ['variable', 'variable2'] },
    ],
    presets: [
      { label: 'd/dx (x³ sin x)', op: 'diff', expr: 'x^3 * sin(x)' },
      { label: '∫ x² eˣ dx', op: 'integrate', expr: 'x^2 * exp(x)' },
      { label: '∫₀³ x² dx', op: 'integrate', expr: 'x^2', params: { lower_bound: '0', upper_bound: '3' } },
      { label: 'lim x→0 sin(x)/x', op: 'limit', expr: 'sin(x)/x', params: { point: '0' } },
      { label: 'Taylor exp(x) n=5', op: 'series', expr: 'exp(x)', params: { order: 5, point: '0' } },
      { label: "y'' + 4y = 0", op: 'ode', expr: 'diff(y(x), x, 2) + 4*y(x)' },
    ],
  },
  linear_algebra: {
    name: 'Linear Algebra',
    description: 'Matrix determinants, inverses, eigenvalues, rank, LU/QR decomposition, and linear systems.',
    operations: [
      { id: 'det', name: 'Determinant det(A)', defaultExpr: '[[1, 2], [3, 4]]', params: [] },
      { id: 'inv', name: 'Matrix Inverse A⁻¹', defaultExpr: '[[4, 7], [2, 6]]', params: [] },
      { id: 'eigen', name: 'Eigenvalues & Eigenvectors', defaultExpr: '[[2, 1], [1, 2]]', params: [] },
      { id: 'rank', name: 'Matrix Rank & RREF', defaultExpr: '[[1, 2, 3], [4, 5, 6], [7, 8, 9]]', params: [] },
      { id: 'lu', name: 'LU Decomposition (P·A = L·U)', defaultExpr: '[[2, -1, -2], [-4, 6, 3], [-4, -2, 8]]', params: [] },
      { id: 'qr', name: 'QR Decomposition (A = Q·R)', defaultExpr: '[[12, -51], [6, 167]]', params: [] },
      { id: 'multiply', name: 'Matrix Multiplication A × B', defaultExpr: '[[1, 2], [3, 4]]', params: ['matrix_b'] },
      { id: 'solve_system', name: 'Solve System Ax = B', defaultExpr: '[[2, 1], [1, -1]]', params: ['vector_b'] },
    ],
    presets: [
      { label: '2×2 Determinant', op: 'det', expr: '[[1, 2], [3, 4]]' },
      { label: 'Eigen [[2,1],[1,2]]', op: 'eigen', expr: '[[2, 1], [1, 2]]' },
      { label: '3×3 Inverse', op: 'inv', expr: '[[1, 0, 2], [2, -1, 3], [4, 1, 8]]' },
      { label: 'Solve Ax = B', op: 'solve_system', expr: '[[3, 2], [1, 4]]', params: { vector_b: '[[18], [16]]' } },
      { label: '3×3 Rank Deficient', op: 'rank', expr: '[[1, 2, 3], [4, 5, 6], [7, 8, 9]]' },
    ],
  },
  algebra: {
    name: 'Algebra & Polynomials',
    description: 'Exact root solving, polynomial factoring, partial fraction decomposition, and simplification.',
    operations: [
      { id: 'solve', name: 'Find Roots / Solve Equation', defaultExpr: 'x^3 - 6*x^2 + 11*x - 6 = 0', params: ['variable'] },
      { id: 'factor', name: 'Factor Polynomial', defaultExpr: 'x^4 - 16', params: [] },
      { id: 'apart', name: 'Partial Fractions Decomposition', defaultExpr: '1 / (x^2 - 5*x + 6)', params: ['variable'] },
      { id: 'simplify', name: 'Simplify Canonical Expression', defaultExpr: '(x^2 - 1)/(x - 1)', params: [] },
      { id: 'expand', name: 'Expand Expression', defaultExpr: '(x + 2)^4', params: [] },
      { id: 'trigsimp', name: 'Trigonometric Simplification', defaultExpr: 'sin(x)^4 - cos(x)^4', params: [] },
    ],
    presets: [
      { label: 'x³-6x²+11x-6 = 0', op: 'solve', expr: 'x^3 - 6*x^2 + 11*x - 6 = 0' },
      { label: 'Factor x⁴ - 16', op: 'factor', expr: 'x^4 - 16' },
      { label: 'Partial Fractions 1/(x²-1)', op: 'apart', expr: '1 / (x^2 - 1)' },
      { label: 'sin⁴x - cos⁴x', op: 'trigsimp', expr: 'sin(x)^4 - cos(x)^4' },
      { label: 'Expand (x+2)⁴', op: 'expand', expr: '(x + 2)^4' },
    ],
  },
  complex: {
    name: 'Complex Analysis',
    description: 'Complex numbers in Cartesian, polar, and Euler exponential form, and nth roots.',
    operations: [
      { id: 'euler', name: 'Polar & Euler Exponential Form', defaultExpr: '3 + 4*I', params: [] },
      { id: 'roots', name: 'N-th Roots (De Moivre)', defaultExpr: '-8', params: ['nth_roots'] },
    ],
    presets: [
      { label: '3 + 4i Form', op: 'euler', expr: '3 + 4*I' },
      { label: 'Cube Roots of -8', op: 'roots', expr: '-8', params: { n: 3 } },
      { label: '4th Roots of Unity (1)', op: 'roots', expr: '1', params: { n: 4 } },
      { label: '1 + i√3 Exponential', op: 'euler', expr: '1 + sqrt(3)*I' },
    ],
  },
  discrete: {
    name: 'Discrete & Statistics',
    description: 'Permutations, combinations, modular arithmetic, inverse, and dataset distributions.',
    operations: [
      { id: 'combinatorics', name: 'Combinatorics C(n, k) & P(n, k)', defaultExpr: '', params: ['n_k'] },
      { id: 'modular', name: 'Modular Arithmetic & Inverse', defaultExpr: '', params: ['a_m'] },
      { id: 'stats', name: 'Descriptive Statistics & Summary', defaultExpr: '12, 15, 14, 10, 18, 19, 22, 16, 17, 15', params: [] },
      { id: 'binomial_dist', name: 'Binomial Distribution PMF', defaultExpr: '', params: ['binomial_params'] },
    ],
    presets: [
      { label: 'C(10, 3) & P(10, 3)', op: 'combinatorics', expr: '', params: { n: 10, k: 3 } },
      { label: '3⁻¹ mod 11', op: 'modular', expr: '', params: { a: 3, m: 11 } },
      { label: 'Dataset Statistics', op: 'stats', expr: '4, 8, 6, 5, 3, 2, 8, 9, 2, 5' },
      { label: 'Binomial (n=20, p=0.4)', op: 'binomial_dist', expr: '', params: { n: 20, p: 0.4, k: 8 } },
    ],
  },
  graphing: {
    name: '2D / 3D Graphing',
    description: 'Interactive visualization for 2D Cartesian curves, 2D parametric paths, and 3D surfaces.',
    operations: [
      { id: 'plot2d', name: '2D Cartesian Function y = f(x)', defaultExpr: 'sin(x) * exp(-0.1*x^2)', params: ['x_bounds'] },
      { id: 'surface', name: '3D Surface z = f(x, y)', defaultExpr: 'sin(sqrt(x^2 + y^2))', params: ['surface_bounds'] },
      { id: 'parametric', name: '2D Parametric Curve x(t), y(t)', defaultExpr: 'sin(3*t)', params: ['parametric_y'] },
    ],
    presets: [
      { label: 'Damped Oscillation', op: 'plot2d', expr: 'sin(x) * exp(-0.1*x^2)' },
      { label: '3D Wave Ripple', op: 'surface', expr: 'sin(sqrt(x^2 + y^2))' },
      { label: '3D Hyperbolic Saddle', op: 'surface', expr: 'x^2 - y^2' },
      { label: 'Lissajous Curve', op: 'parametric', expr: 'sin(3*t)', params: { y_expr: 'cos(2*t)', t_min: 0, t_max: 6.28 } },
    ],
  },
};

export const KEYPAD_DATA = {
  calculator: [
    { label: '7', insert: '7' },
    { label: '8', insert: '8' },
    { label: '9', insert: '9' },
    { label: '÷', insert: ' / ' },
    { label: '√x', insert: 'sqrt(' },
    { label: '∛x', insert: 'cbrt(' },
    { label: '(', insert: '(' },
    { label: ')', insert: ')' },

    { label: '4', insert: '4' },
    { label: '5', insert: '5' },
    { label: '6', insert: '6' },
    { label: '×', insert: ' * ' },
    { label: 'x²', insert: '^2' },
    { label: 'xʸ', insert: '^' },
    { label: '%', insert: '%' },
    { label: '1/x', insert: '1/(' },

    { label: '1', insert: '1' },
    { label: '2', insert: '2' },
    { label: '3', insert: '3' },
    { label: '−', insert: ' - ' },
    { label: 'log₁₀', insert: 'log10(' },
    { label: 'ln', insert: 'ln(' },
    { label: '|x|', insert: 'abs(' },
    { label: 'n!', insert: 'factorial(' },

    { label: '0', insert: '0' },
    { label: '.', insert: '.' },
    { label: '±', insert: '-' },
    { label: '+', insert: ' + ' },
    { label: 'π', insert: 'pi' },
    { label: 'e', insert: 'E' },
    { label: 'mod', insert: ' % ' },
    { label: 'gcd', insert: 'gcd(' },
  ],
  basic: [
    { label: '+', insert: ' + ' },
    { label: '−', insert: ' - ' },
    { label: '×', insert: ' * ' },
    { label: '÷', insert: ' / ' },
    { label: '%', insert: '%' },
    { label: '^', insert: '^' },
    { label: '(', insert: '(' },
    { label: ')', insert: ')' },
    { label: 'x', insert: 'x' },
    { label: 'y', insert: 'y' },
    { label: 'z', insert: 'z' },
    { label: 't', insert: 't' },
    { label: 'π', insert: 'pi' },
    { label: 'e', insert: 'E' },
    { label: 'i', insert: 'I' },
    { label: '√x', insert: 'sqrt(' },
    { label: 'x²', insert: '^2' },
    { label: '1/x', insert: '1/(' },
    { label: '|x|', insert: 'abs(' },
    { label: 'log₁₀', insert: 'log10(' },
  ],
  calculus: [
    { label: 'd/dx', insert: 'diff(f, x)' },
    { label: '∫', insert: 'integrate(f, x)' },
    { label: 'lim', insert: 'limit(f, x, 0)' },
    { label: "y''", insert: 'diff(y(x), x, 2)' },
    { label: "y'", insert: 'diff(y(x), x)' },
    { label: 'y(x)', insert: 'y(x)' },
    { label: 'ln', insert: 'log(' },
    { label: 'exp', insert: 'exp(' },
    { label: '∞', insert: 'oo' },
    { label: 'Σ', insert: 'Sum(' },
  ],
  trig: [
    { label: 'sin', insert: 'sin(' },
    { label: 'cos', insert: 'cos(' },
    { label: 'tan', insert: 'tan(' },
    { label: 'asin', insert: 'asin(' },
    { label: 'acos', insert: 'acos(' },
    { label: 'atan', insert: 'atan(' },
    { label: 'sinh', insert: 'sinh(' },
    { label: 'cosh', insert: 'cosh(' },
    { label: 'tanh', insert: 'tanh(' },
  ],
  matrix: [
    { label: '[ [ ] ]', insert: '[[1, 0], [0, 1]]' },
    { label: '3×3 I', insert: '[[1, 0, 0], [0, 1, 0], [0, 0, 1]]' },
    { label: 'det()', insert: 'det(' },
    { label: 'inv()', insert: 'inv(' },
    { label: 'col [ ]', insert: '[[1], [2]]' },
    { label: ',', insert: ', ' },
    { label: '[', insert: '[' },
    { label: ']', insert: ']' },
  ],
};
